import './globals.css'
import RootStyleRegistry from './emotion';
import MyAppShell from '@/components/app-shell';


export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <head>
        <title>数字藏品</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-sacle=1, maximum-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <RootStyleRegistry>
          <MyAppShell >{children}</MyAppShell>
        </RootStyleRegistry>
      </body>
    </html>
  )
}



