import Link from 'next/link'
import FootNav from './components/foot-nav'
import './globals.css'

export const dynamic = 'force-dynamic'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <head>
        <title>数组藏品</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-sacle=1, maximum-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Header />
        {children}
        <FootNav />
      </body>
    </html>
  )
}

function Header() {
  return <div className=' shadow-sm h-16 flex items-center px-5'>
    <Link href={'/'} className='text-2xl font-bold' >Home</Link>
  </div>
}


